/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.text.*;
/**
 *
 * @author Amy Zhang
 * Date: October 12, 2023
 * A Student Grades Application that simulates a grade book for a class with 30 students who each have four test scores
 */
public class StudentGrades extends javax.swing.JFrame {
    String[][] gradesBook = new String[30][6];
    int current = 0; 
    
    //List update
    public void updateList(){
        txtList.setText("");
        for (String[] student : gradesBook){
            if (student[0] != null){ //use current instead?
                //will error if name is smaller than 2 letters
                txtList.append(student[0].substring(0, 1).toUpperCase() + student[0].substring(1) + " " 
                        + student[1].substring(0, 1).toUpperCase() + student[1].substring(1) + ": " 
                        + student[2] + "%, " + student[3] + "%, " + student[4] + "%, " + student[5] + "%\n");
            }
        }
        
        //name, last name, grade1, grade2, grade3, grade4
    }
    
    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtList = new javax.swing.JTextArea();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblTest1 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        lblTest4 = new javax.swing.JLabel();
        lblTest3 = new javax.swing.JLabel();
        txtTest1 = new javax.swing.JTextField();
        txtTest2 = new javax.swing.JTextField();
        txtTest3 = new javax.swing.JTextField();
        txtTest4 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnStudentAverage = new javax.swing.JButton();
        btnCourseAverages = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 255));
        lblTitle.setText("Student Grades");

        lblFirstName.setText("First Name:");

        txtList.setEditable(false);
        txtList.setColumns(20);
        txtList.setLineWrap(true);
        txtList.setRows(5);
        txtList.setPreferredSize(new java.awt.Dimension(10, 84));
        jScrollPane1.setViewportView(txtList);

        lblLastName.setText("Last Name:");

        lblTest1.setText("Test 1");

        lblTest2.setText("Test 2");

        lblTest4.setText("Test 4");

        lblTest3.setText("Test 3");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnStudentAverage.setText("Student Average");
        btnStudentAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentAverageActionPerformed(evt);
            }
        });

        btnCourseAverages.setText("Course Averages");
        btnCourseAverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseAveragesActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setText(" ");

        txtAverage.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTest2)
                            .addComponent(lblTest1)
                            .addComponent(lblTest4)
                            .addComponent(lblTest3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTest3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtTest2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtTest1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTest4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addComponent(txtAverage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnStudentAverage)
                        .addGap(18, 18, 18)
                        .addComponent(btnCourseAverages))
                    .addComponent(btnAdd)
                    .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest1)
                            .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest2)
                            .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest3)
                            .addComponent(txtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest4)
                            .addComponent(txtTest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStudentAverage)
                            .addComponent(btnCourseAverages))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //check if at capacity
        if (current == 30){
            lblError.setText("The class is at capacity");
            return;
        }
        
        String firstName = txtFirstName.getText().toLowerCase(), lastName = txtLastName.getText().toLowerCase();
        String test1 = txtTest1.getText(), test2 = txtTest2.getText(), test3 = txtTest3.getText(), test4 = txtTest4.getText();
        
        //check empty/valid values
        if (firstName.equals("") || lastName.equals("") || test1.equals("") || test2.equals("") || test3.equals("") || test4.equals("")){
            lblError.setText("You left a required piece of information empty");   
            return;
        }
        
        //check if repeat
        for (String[] student : gradesBook){
            if (firstName.equals(student[0]) && lastName.equals(student[1])) {
                lblError.setText("Student already exists"); 
                return;
            }
        }
        
        //check numbers
        try {
            double dblTest1 = Double.parseDouble(txtTest1.getText());
            double dblTest2 = Double.parseDouble(txtTest2.getText());
            double dblTest3 = Double.parseDouble(txtTest3.getText());
            double dblTest4 = Double.parseDouble(txtTest4.getText());
            if (dblTest1 > 100 || dblTest1 < 0 || dblTest2 > 100 || dblTest2 < 0 || dblTest3 > 100 || dblTest3 < 0 || dblTest4 > 100 || dblTest4 < 0) {
            lblError.setText("You must enter a number between 0-100 for the grades");
            return;
            }
        } catch(NumberFormatException e){
            lblError.setText("You must enter a number for the grades");   
            return;
        }
            
        //add to array
        gradesBook[current][0] = firstName;
        gradesBook[current][1] = lastName;
        gradesBook[current][2] = test1;
        gradesBook[current][3] = test2;
        gradesBook[current][4] = test3;
        gradesBook[current][5] = test4;
        current++;
        
        updateList();
        //Clearing textfields
        lblError.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtTest1.setText("");
        txtTest2.setText("");
        txtTest3.setText("");
        txtTest4.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnStudentAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentAverageActionPerformed
        DecimalFormat df2 = new DecimalFormat("0.00");
        String firstName = txtFirstName.getText().toLowerCase(), lastName = txtLastName.getText().toLowerCase();
        
        lblError.setText("");
        
        //check empty/valid values
        if (firstName.equals("") || lastName.equals("")){
            lblError.setText("You need to enter a student's first and last name");   
            return;
        }
        
        //check if exists
        for (String[] student : gradesBook){
            if (firstName.equals(student[0]) && lastName.equals(student[1])) {
                txtAverage.setText(student[0].substring(0, 1).toUpperCase() + student[0].substring(1) + " " 
                        + student[1].substring(0, 1).toUpperCase() + student[1].substring(1) + "\'s average is " +
                        df2.format((Double.parseDouble(student[2]) + Double.parseDouble(student[3]) + Double.parseDouble(student[4]) + Double.parseDouble(student[5])) / 4) + "%");
                return;
            }
        }
        lblError.setText("Student does not exist");         
    }//GEN-LAST:event_btnStudentAverageActionPerformed

    private void btnCourseAveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseAveragesActionPerformed
        DecimalFormat df2 = new DecimalFormat("0.00");lblError.setText("");
        double total = 0;
        
        //loop through each student and to total
        for (String[] student : gradesBook){
            if (student[0] != null){ //use current instaed
                total += Double.parseDouble(student[2]) + Double.parseDouble(student[3]) + Double.parseDouble(student[4]) + Double.parseDouble(student[5]);
            }
        }
        //divide by total students
        if (current > 0){
            txtAverage.setText("Course average is: " + df2.format(total / (current * 4)) + "%");
        } else {
            lblError.setText("No students entered");
        }
    }//GEN-LAST:event_btnCourseAveragesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCourseAverages;
    private javax.swing.JButton btnStudentAverage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JLabel lblTest4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextArea txtList;
    private javax.swing.JTextField txtTest1;
    private javax.swing.JTextField txtTest2;
    private javax.swing.JTextField txtTest3;
    private javax.swing.JTextField txtTest4;
    // End of variables declaration//GEN-END:variables
}
